### ISSUE TITLE
Providing host as parameter

### ISSUE THREAD

**Issue by morazow** [etsy/Sahale#2]
Instead of hard coding the monitoring server in _flow-tracker.properties_ file, would it be good idea to provide it as parameter to cascading/scalding jobs? 

Similar to --track-job also provide --host & --port?

This way re-assemblying fat jar won't be needed if host server changes.

**Comment by morazow** [comment]
Please let me know if this is good idea. Then maybe I can send a pull request.

**Comment by initialcontext** [comment]
Hi! I don't think its a bad idea at all. I think the reason we didn't go that route from the get-go is it's a little counter to Etsy's internal use pattern, but no reason not to do it. Feel free to send a pull request if you like. Thanks for asking.

**Comment by initialcontext** [comment]
Hey, what about "--track-job host:port" to keep it concise rather than add new switches?

**Comment by morazow** [comment]
@initialcontext yes, that is nice idea. 
I will give it a shot.

**Comment by initialcontext** [comment]
one of my coworkers thought of it but thank you :)

**Comment by initialcontext** [comment]
I just pushed an update adding a --server arg to TrackedJob that will override the server host:port set in the properties file. It still defaults to the properties file settings if no arg is present. Example use:

`bin/runjob com.your.job.class.Name --input indir --output outdir … --server http://my.server:port`
