### ISSUE TITLE
Support pluggable username linking

### ISSUE THREAD

**Issue by initialcontext** [etsy/Sahale#5]
Internally Etsy has a great staff directory that we link to from the displayed usernames in Sahale. Make this pluggable so others can take advantage of this easily.

**Comment by initialcontext** [comment]
@ajsquared hey I think your configurable link patch for the logs can be used to resolve this issue, correct?

**Comment by ajsquared** [comment]
We could put the username link there, but I think it would also be useful to have the username in the list of jobs link to wherever.  My patch wouldn't address that case.
