### ISSUE TITLE
Release Tags

### ISSUE THREAD

**Issue by thatjpk** [etsy/Sahale#66]
Greetings!  I have a small request:  When you cut a Sahale release, would you kindly tag it and push the tag to github?  Currently, I only see a v1.1.0 and a v0.5 tag.  

I'm automating a deployment of the node application, and to get v2.0.1 I have to poke through the commit history to find the commit where that version was set in pom.xml and use that commit's hash as the git ref in config management.  I'd much rather just have a tag.

Thanks for your consideration!

**Comment by dossett** [comment]
That is a fine request @thatjpk, we will!  Please ping us if we forget.  We're glad that you use Sahale and find it useful.

**Comment by thatjpk** [comment]
Awesome, thanks!
