### ISSUE TITLE
Include glue code and example jobs targeting other Cascading DSLs

### ISSUE THREAD

**Issue by initialcontext** [etsy/Sahale#7]
Like the pure Java API in Cascading, Cascalog, etc.

Pull requests welcome. I'll take a swipe at this myself sooner or later but its low priority as Etsy's piece of the Cascading landscape really focuses on Scalding.

**Comment by ajsquared** [comment]
We're not going to pursue this currently.  Pull requests are still welcome if anyone wants to provide examples for DSLs besides Scalding.
